### ISSUE TITLE
Consider builds using sbt using these libraries

### ISSUE THREAD

**Issue by PhilAndrew** [woq-blended/blended#58] opened 2015-08-06 09:52 UTC
https://github.com/wav/osgi-tooling

https://github.com/sbt/sbt-osgi

**Comment by lefou** [comment] 2015-08-06 11:15
Thanks for your interest. 

This is a duplicate of https://github.com/woq-blended/blended/issues/9. Please read the existing discussion. We'd like to hear your opinion as well.

If you need help with the current build setup let us know. So we will better learn what is missing in the current documentation.

**Closed by lefou** 2015-08-06 11:15 UTC
Labels: duplicate
